using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generators.BinarySerializer
{
    [Generator]
    public class BinarySerializerGenerator : IIncrementalGenerator
    {
        private const string AttributeMetadataName = "Generators.BinarySerializer.GenerateBinarySerializerAttribute";

        private static readonly DiagnosticDescriptor MissingPartialModifier = new(
            id: "BINSER001",
            title: "Class with [GenerateBinarySerializer] attribute must be as partial",
            messageFormat: "Class '{0}' is not a partial",
            category: "Generators.BinarySerializer",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true
        );

        /// <inheritdoc />
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            const string attributeSource =
                """
                namespace Generators.BinarySerializer
                {
                    [System.AttributeUsage(System.AttributeTargets.Class)]
                    public sealed class GenerateBinarySerializerAttribute : System.Attribute
                    {
                    }
                }
                """;

            context.RegisterPostInitializationOutput(ctx =>
                {
                    ctx.AddSource(
                        hintName: "GenerateBinarySerializerAttribute.g.cs",
                        sourceText: SourceText.From(attributeSource, Encoding.UTF8)
                    );
                }
            );

            var classes = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: AttributeMetadataName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.TargetNode
                );

            context.RegisterSourceOutput(
                source: classes.Combine(context.CompilationProvider),
                action: static (spc, source) => Generate(source.Right, source.Left, spc)
            );
        }

        private static void Generate(Compilation compilation, ClassDeclarationSyntax classSyntax, SourceProductionContext spc)
        {
            var symbol = compilation.GetSemanticModel(classSyntax.SyntaxTree).GetDeclaredSymbol(classSyntax);

            if (symbol is null || symbol.IsGenericType || symbol.ContainingType is not null)
            {
                return;
            }

            if (!classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                spc.ReportDiagnostic(Diagnostic.Create(MissingPartialModifier, classSyntax.GetLocation(), symbol.Name));

                return;
            }

            var code = new StringBuilder();
            code.AppendLine("// <auto-generated/>");
            code.AppendLine("#nullable enable");
            code.AppendLine();
            code.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()}");
            code.AppendLine("{");
            code.AppendLine($"    partial class {symbol.Name}");
            code.AppendLine("    {");
            code.AppendLine("        public void SerializeToBinary(global::System.IO.Stream stream)");
            code.AppendLine("        {");
            code.AppendLine(
                "            using var bw = new global::System.IO.BinaryWriter(stream, global::System.Text.Encoding.UTF8, leaveOpen: true);"
            );

            var properties = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.GetMethod != null)
                .ToList();

            foreach (var property in properties)
            {
                var bwWrite = GetWriteByType(property);

                if (bwWrite is null)
                {
                    continue;
                }

                code.AppendLine($"            {bwWrite}");
            }

            code.AppendLine("        }");
            code.AppendLine("    }");
            code.AppendLine("}");

            spc.AddSource(
                hintName: $"{symbol.ToDisplayString()}.BinarySerializer.g.cs",
                sourceText: SourceText.From(code.ToString(), Encoding.UTF8)
            );
        }

        private static string GetWriteByType(IPropertySymbol property)
        {
            if (property.Type.TypeKind == TypeKind.Enum)
            {
                return $"bw.Write((int){property.Name});";
            }

            return property.Type.SpecialType switch
            {
                SpecialType.System_Boolean or
                    SpecialType.System_Byte or
                    SpecialType.System_SByte or
                    SpecialType.System_Int16 or
                    SpecialType.System_UInt16 or
                    SpecialType.System_Int32 or
                    SpecialType.System_UInt32 or
                    SpecialType.System_Int64 or
                    SpecialType.System_UInt64 or
                    SpecialType.System_Single or
                    SpecialType.System_Double or
                    SpecialType.System_Decimal or
                    SpecialType.System_Char or
                    SpecialType.System_String => $"bw.Write({property.Name});",
                _ => property.Type.ToDisplayString() switch
                {
                    "System.DateTime" => $"bw.Write({property.Name}.ToBinary());",
                    "System.Guid" => $"bw.Write({property.Name}.ToByteArray());",
                    _ => null
                }
            };
        }
    }
}